name: bump-version

on: workflow_dispatch

env:
  BUMP_USERNAME: Mr Bump
  BUMP_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  bump:
    name: bump-version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: install-python
        uses: actions/setup-python@v4
        with:
          python-version-file: .python-version

      - name: install-uv
        uses: astral-sh/setup-uv@v3

      - name: install-dependencies
        run: uv sync --frozen --group docs

      - name: set-git-identity
        run: |
          git config user.name "$BUMP_USERNAME"
          git config user.email "$BUMP_EMAIL"

      - name: bump-version
        run: uv run cz bump --annotated-tag --yes

      - name: open-pull-request
        run: |
          git checkout -b bump-version
          git push --follow-tags --set-upstream origin bump-version
          gh pr create --base main --head bump-version --fill
