name: cd
on: workflow_dispatch
jobs:
  bump:
    name: bump-version
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.BUMP_APP_ID }}
          private-key: ${{ secrets.BUMP_APP_SECRET }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - uses: astral-sh/setup-uv@v3
      - run: |
          git config user.name "${{ vars.BUMP_APP_USER_NAME }}"
          git config user.email "${{ vars.BUMP_APP_USER_EMAIL }}"
          git checkout main
          uv sync --frozen --group bump
          uv run cz bump --annotated-tag --yes
          git push --follow-tags
  docs:
    name: deploy-docs
    permissions:
      contents: write
    needs: bump
    runs-on: ubuntu-latest
    env:
      COVERAGE_BADGE: docs/reports/test-coverage.svg
      COVERAGE_MD: docs/reports/test-coverage.md
      COVERAGE_XML: docs/reports/test-coverage.xml
      TESTS_BADGE: docs/reports/tests.svg
      TESTS_XML: docs/reports/tests.xml
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.BUMP_APP_ID }}
          private-key: ${{ secrets.BUMP_APP_SECRET }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - uses: astral-sh/setup-uv@v3
      - run: |
          uv sync --frozen --group docs --group test
          uv run pytest --junitxml="$TESTS_XML"
          uv run coverage xml -o "$COVERAGE_XML"
          uv run coverage report --format=markdown > "$COVERAGE_MD"
          uv run genbadge tests --input-file "$TESTS_XML" --output-file "$TESTS_BADGE"
          uv run genbadge coverage --input-file "$COVERAGE_XML" --output-file "$COVERAGE_BADGE"
          uv run mkdocs build
          uv run mkdocs gh-deploy
