name: cd

on: 
  workflow_dispatch

env:
  BUMP_USERNAME: Mr Bump
  BUMP_EMAIL: bump@users.noreply.github.com
  COVERAGE_BADGE: reports/coverage/badge.svg
  COVERAGE_RESULTS: reports/coverage/results.xml
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TESTS_BADGE: reports/tests/badge.svg
  TESTS_RESULTS: reports/tests/results.xml
  
jobs:
  cd:
    name: bump
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: install-python
        uses: actions/setup-python@v4
        with:
          python-version-file: .python-version

      - name: install-uv
        uses: astral-sh/setup-uv@v3

      - name: install-dependencies
        run: uv sync --group bump

      - name: run-tests
        run: |
          uv run pytest --junitxml="$TESTS_RESULTS"
          uv run coverage xml -o "$COVERAGE_RESULTS"

      - name: generate-badges
        run: |
          uv run genbadge tests --input-file "$TESTS_RESULTS" --output-file "$TESTS_BADGE"
          uv run genbadge coverage --input-file "$COVERAGE_RESULTS" --output-file "$COVERAGE_BADGE"

      - name: set-git-identity
        run: |
          git config user.name "$BUMP_USERNAME"
          git config user.email "$BUMP_EMAIL"

      - name: bump-version
        run: uv run cz bump

      - name: open-pull-request
        run: |
          git checkout -b bump-version
          git push --follow-tags --force --set-upstream origin bump-version
          gh pr create --base main --head bump-version --fill
