name: ci

on: 
  pull_request

jobs:
  lint:
    name: run-linters
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install-python
        uses: actions/setup-python@v4
        with:
          python-version-file: .python-version

      - name: install-uv
        uses: astral-sh/setup-uv@v3

      - name: install-dependencies
        run: uv sync --group lint

      - name: run-linters
        run: uv run ./scripts/lint.sh
  
  test:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install-python
        uses: actions/setup-python@v4
        with:
          python-version-file: .python-version

      - name: install-uv
        uses: astral-sh/setup-uv@v3

      - name: install-dependencies
        run: uv sync --group test

      - name: run-tests
        run: uv run pytest --no-cov