name: ci

on: pull_request

jobs:
  lint:
    name: run-linters
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install-uv
        uses: astral-sh/setup-uv@v3

      - name: run-linters
        run: |
          uv sync --group lint
          uv run ruff format --check
          uv run ruff check
          uv run mypy
  
  test:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install-uv
        uses: astral-sh/setup-uv@v3

      - name: run-tests
        run: |
          uv sync --group test
          uv run pytest --no-cov