name: deploy-docs

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  COVERAGE_BADGE: docs/reports/coverage/badge.svg
  COVERAGE_HTML: docs/reports/coverage/report/
  COVERAGE_XML: docs/reports/coverage/results.xml
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TESTS_BADGE: docs/reports/tests/badge.svg
  TESTS_HTML: docs/reports/tests/report.html
  TESTS_XML: docs/reports/tests/results.xml
  
jobs:
  bump:
    name: deploy-docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: install-uv
        uses: astral-sh/setup-uv@v3

      - name: install-dependencies
        run: uv sync --frozen --group docs

      - name: run-tests
        run: |
          uv run pytest --junitxml="$TESTS_XML" --html="$TESTS_HTML"
          uv run coverage xml -o "$COVERAGE_XML"
          uv run coverage html --directory "$COVERAGE_HTML"

      - name: generate-badges
        run: |
          uv run genbadge tests --input-file "$TESTS_XML" --output-file "$TESTS_BADGE"
          uv run genbadge coverage --input-file "$COVERAGE_XML" --output-file "$COVERAGE_BADGE"

      - name: deploy-docs
        run: |
          uv run mkdocs build
          uv run mkdocs gh-deploy
