name: lint

on: 
  pull_request

jobs:
  ci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up python
        uses: actions/setup-python@v4

      - name: install dependencies
        run: pip install -r requirements/linting.txt

      - name: lint
        run: . scripts/lint.sh
